import { Ubuntu_Sans } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const ubuntu = Ubuntu_Sans({
	subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: {
    default: "Open Social",
    template: "%s | Open Social"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={`${ubuntu.className} h-full antialiased`} >
      <body>{children}</body>
    </html>
  );
}
